### PR TITLE
Bug/issue 2 run in sd test not working

### LINKED ISSUE #2: bin/runInSdTest.sh uses wrong working directory

### PR DESCRIPTION
**Pull request by twojtylak**
fixes #2

### CODE REVIEW

**Review by sd-lueckel — DISMISSED** [review]

File: bin/runInSdTest.sh [hunk 1]
```diff
@@ -27,6 +27,6 @@ PROJECT_DIR="$( dirname $( dirname $( dirname "${PACKAGE_DIR}") ) )"
 PROJECT_NAME="$( basename ${PROJECT_DIR} | tr '[:upper:]' '[:lower:]' )"
 # TODO: Think about a good solution for a different shopware version
 PHP_CONTAINER_NAME="${PROJECT_NAME}_shopware546_php${VERSION}_1"
+WORK_DIR="/var/www/shopware54_php${VERSION}"
```
Comment (michz) [inline bin/runInSdTest.sh]: I'm not happy that you removed the ability to change the workdir from outside bash script.
_(EDIT: I mean from "outside the bash script", not "outside the container")_

What do you think about following?

```
WORK_DIR=${WORK_DIR:-"/var/www/shopware54_php${VERSION}"}
```

**Review by michz — CHANGES_REQUESTED** [review]

File: bin/runInSdTest.sh (hunk 1 above)
Comment (twojtylak) [reply bin/runInSdTest.sh]: Ah okay. I never got the idea to change the workdir by argument.
You want to be able to call e.g.
```
vendor/bin/runInSdTest.sh 72 WORK_DIR="var/www" bin/console sw:cache:clear
```
right?

Unfortunately we need to exclude this argument in the docker exec because all parameters except the first one are passed to docker exec.

Also it would break, at the moment, if workdir is passed as first argument.

Comment (michz) [reply bin/runInSdTest.sh]: No, I want to be able to do this:

```
WORK_DIR="/somewhere/else" vendor/bin/runInSdTest.sh 72 bin/console sw:cache:clear
```

This passes WORK_DIR as environment variable to the called script, without adding it to the global environment of the current shell.

See also for an explanation (with definition) :
https://unix.stackexchange.com/a/126942

Comment (twojtylak) [reply bin/runInSdTest.sh]: 👍 ah okay thats fine (and working). I will change it.

**Review by michz — APPROVED** [review]

**Review by sd-lueckel — APPROVED** [review]
